const INIT_LOGIN_PROCESS = "INIT_LOGIN_PROCESS";
const LOGIN_PROCESS_SUCCESS = "LOGIN_PROCESS_SUCCESS";
const LOGIN_PROCESS_FAILURE = "LOGIN_PROCESS_FAILURE";

export { INIT_LOGIN_PROCESS, LOGIN_PROCESS_SUCCESS, LOGIN_PROCESS_FAILURE };
