const INIT_LOGIN_PROCESS = "INIT_LOGIN_PROCESS";
const LOGIN_PROCESS_SUCCESS = "LOGIN_PROCESS_SUCCESS";
const LOGIN_PROCESS_FAILURE = "LOGIN_PROCESS_FAILURE";
const LOGOUT_PROCESS = "LOGOUT_PROCESS";
const INIT_PROFILE_UPDATE = "INIT_PROFILE_UPDATE";
const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
const PROFILE_UPDATE_FAILURE = "PROFILE_UPDATE_FAILURE";

export {
  INIT_LOGIN_PROCESS,
  LOGIN_PROCESS_SUCCESS,
  LOGIN_PROCESS_FAILURE,
  LOGOUT_PROCESS,
  INIT_PROFILE_UPDATE,
  PROFILE_UPDATE_SUCCESS,
  PROFILE_UPDATE_FAILURE,
};
